title: "Saumitra Mazumder"
author: "Saumitra"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header
katex: true

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home", icon: home}
  - {file: "math.md", title: "Math", icon: infinity}
  - {file: "kilos.md", title: "Kilos", icon: dumbbell}
  - {file: "on.md", title: "On ... and other ramblings", icon: coffee}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/samazumder/"}
 # - {title: Instagram, icon: instagram, url: "https://www.instagram.com/tennessee_tobacco/"}
  - {title: Github, icon: github, url: "https://github.com/SAMazumder"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
